apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard  # Change if your cluster uses a different storage class

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.56
          ports:
            - containerPort: 16686  # UI
            - containerPort: 14268  # Collector
            - containerPort: 6831   # Agent (UDP)
            - containerPort: 6832   # Agent (UDP)
          volumeMounts:
            - name: jaeger-storage
              mountPath: /badger
          env:
            - name: SPAN_STORAGE_TYPE
              value: badger
            - name: BADGER_DIRECTORY_VALUE
              value: /badger/data
            - name: BADGER_DIRECTORY_KEY
              value: /badger/key
      volumes:
        - name: jaeger-storage
          persistentVolumeClaim:
            claimName: jaeger-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    app: jaeger
  ports:
    - name: ui
      port: 80
      targetPort: 16686
    - name: collector
      port: 14268
      targetPort: 14268
    - name: agent-udp1
      port: 6831
      protocol: UDP
      targetPort: 6831
    - name: agent-udp2
      port: 6832
      protocol: UDP
      targetPort: 6832
