adminPassword: admin

persistence:
  enabled: true
  size: 5Gi

service:
  type: LoadBalancer

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.observability.svc.cluster.local:3100
      - name: Jaeger
        type: jaeger
        access: proxy
        url: http://jaeger-query.observability.svc.cluster.local
