mode: deployment

config:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

  exporters:
    logging:
      loglevel: debug
    otlp:
      endpoint: jaeger-collector.observability.svc.cluster.local:4317

  processors:
    batch: {}

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [logging, otlp]
