apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  selector:
    app: otel-collector
  ports:
    - port: 4317
      name: grpc
      targetPort: 4317
    - port: 4318
      name: http
      targetPort: 4318
